# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 967b695b3b2d78131b36944901195439a8f1fe2f2479279ee0701169f4064873f038f7328906a50e39e444c3402ef49114ce79994f77421c57100fa7e177b53f

test:
  secret_key_base: 967b695b3b2d78131b36944901195439a8f1fe2f2479279ee0701169f4064873f038f7328906a50e39e444c3402ef49114ce79994f77421c57100fa7e177b53f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
